### ISSUE TITLE
Issue with swagger

### ISSUE THREAD

**Issue by herryyannara** [DevExpress-Examples/xpo-json-serialization#16]
creating a new project with VS2019 + net core 5, template web API core  with swagger support, swagger always not responding when try out on POST method

**Comment by Uriahas** [comment]
@herryyannara, I could not reproduce this issue, but I noticed that Swashbuckle includes too many properties in the automatically generated schema. Try adding a custom [Schema Filter](https://github.com/domaindrivendev/Swashbuckle.AspNetCore#schema-filters) that exposes only persistent properties:

```cs
using System.Linq;

using DevExpress.Xpo.Metadata;

using Microsoft.OpenApi.Models;

using Swashbuckle.AspNetCore.SwaggerGen;

namespace DxSample.Swagger {
    sealed class XpoSchemaFilter : ISchemaFilter {
        readonly XPDictionary dictionary = new ReflectionDictionary();
        void ISchemaFilter.Apply(OpenApiSchema schema, SchemaFilterContext context) {            
            XPClassInfo ci = dictionary.QueryClassInfo(context.Type);
            if(ci != null ) {
                schema.Type = "object";
                schema.Properties = ci.PersistentProperties.Cast<XPMemberInfo>().ToDictionary(mi => mi.Name, 
                    mi => context.SchemaGenerator.GenerateSchema(mi.MemberType, context.SchemaRepository));
            }
        }
    }
}
```

If this does not help, please submit a ticket on our [Support Center](https://support.devexpress.com).
